apiVersion: v1
kind: Secret
metadata:
  name: app-config
data:
  appsettings.json: |-
    {
      "ConnectionStrings": {
      "DefaultConnection": "Data Source=cheetasv3sql;Initial Catalog=CheetasDb;Persist Security Info=True;User ID=sa;Password=ZAQ!2wsx",
      "RabbitMQ": "amqp://guest:guest@cheetasv3rbt:5672",
      "SQLiteConnection": "DataSource=example.db"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      }
    }