apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: dotnetcore32base-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetcore32base
  template:
    metadata:
      labels:
        app: dotnetcore32base
    spec:
      containers:
      - name: dotnetcore32base
        image: pforsthoff/dotnetcore32base:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: dotnetcore32base-service
spec:
  selector:
    app: dotnetcore32base
  ports:
    - name: http
      port: 80
      targetPort: 80 # Default port for image
  type: LoadBalancer
